--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/ktpmpl-cfs
build-by-default: true
branches:
- main
- pm4
- pm4-updatenotifier
projects:
  ktpmpl-cfs:
    path: ""
    model: virion
    type: library
    libs:
    - src: ifera-mc/UpdateNotifier/UpdateNotifier
      version: ^2.2.0
      branch: API-4.0.0
...
