--- # Poggit-CI manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/ktpmpl-cfs
build-by-default: true
branches:
- main
- 2.0.0
projects:
  ktpmpl-cfs:
    path: ""
    model: virion
    type: library
    libs:
    - src: ifera-mc/UpdateNotifier/UpdateNotifier
      version: ^2.2.0
      branch: API-4.0.0
  KtpmplCfsTest:
    path: "tests/KtpmplCfsTest"
    libs:
    - src: thebigcrafter/ktpmpl-cfs/ktpmpl-cfs
      branch: main
      version: 4.0.0
...
