--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/ktpmpl-cfs
build-by-default: true
branches:
- main
- pm4
projects:
  ktpmpl-cfs:
    path: ""
    model: virion
    type: library
...
